name: prosafeai github actions
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  build-prosafeAI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: './'
          target: /home/sunck/prosafeai/
        
  deploy-prosafeAI:
    needs: build-prosafeAI
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: "deploy"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            pwd
            ./tt.sh
            # /tt.sh
            # docker images
            # docker ps -a
            # docker login --username=a18604558122 -p=13763405168YUmiao registry.cn-hangzhou.aliyuncs.com
            # echo "$PASSWORD" | docker login --username a18604558122 --password-stdin registry.cn-hangzhou.aliyuncs.com
            # ifconfig
            # docker images
            # docker pull registry.cn-hangzhou.aliyuncs.com/sunck_images_01/ubuntu:v4.0
            # docker images
            # docker run -d -p 8000:8000 registry.cn-hangzhou.aliyuncs.com/sunck_images_01/ubuntu:v4.0 /root/code/manage.py 0.0.0.0:8000
